name: Podcast API CICD

on:
  push:
  workflow_dispatch:

env:
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}

jobs:
  provision-acr:
    runs-on: ubuntu-latest
    outputs:
      acr_name: ${{ steps.tf-outputs.outputs.ACR_NAME }}
      acr_login_server: ${{ steps.tf-outputs.outputs.ACR_LOGIN_SERVER }}
      acr_username: ${{ steps.tf-outputs.outputs.ACR_USERNAME }}
      acr_password: ${{ steps.tf-outputs.outputs.ACR_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Initialize Terraform
        run: terraform init -upgrade
        working-directory: ./infra/api

      - name: Plan Terraform
        run: terraform validate; terraform plan -no-color
        working-directory: ./infra/api

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./infra/api

      - name: Get Terraform Outputs
        id: tf-outputs
        run: |
          echo "ACR_NAME=$(terraform output -raw acr_name)" >> $GITHUB_ENV
          echo "ACR_LOGIN_SERVER=$(terraform output -raw acr_login_server)" >> $GITHUB_ENV
          echo "ACR_USERNAME=$(terraform output -raw acr_username)" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$(terraform output -raw acr_password)" >> $GITHUB_ENV
        working-directory: ./infra/api

  build-application:
    runs-on: ubuntu-latest
    needs: provision-acr
    steps:
      - name: Checkout
        uses: actions/checkout@v2      

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ needs.provision-acr.outputs.acr_login_server }}
          username: ${{ needs.provision-acr.outputs.acr_username }}
          password: ${{ needs.provision-acr.outputs.acr_password }}     

      - uses: actions/setup-dotnet@v3

      - name: Build Podcast Updater
        run: dotnet publish -c Release -r linux-x64 /t:PublishContainer src/Services/Podcasts/Podcast.Updater.Worker/Podcast.Updater.Worker.csproj -p ContainerRegistry=${{ needs.provision-acr.outputs.acr_login_server }} -p ContainerImageTag=${{ github.sha }}

      - name: Build Podcast API
        run: dotnet publish -c Release -r linux-x64 -p ContainerRegistry=${{ needs.provision-acr.outputs.acr_login_server }} -p ContainerImageTag=${{ github.sha }} -p PublishProfile=DefaultContainer src/Services/Podcasts/Podcast.API/Podcast.API.csproj

      - name: Build Podcast Ingestion
        run: dotnet publish -c Release -r linux-x64 /t:PublishContainer src/Services/Podcasts/Podcast.Ingestion.Worker/Podcast.Ingestion.Worker.csproj -p ContainerRegistry=${{ needs.provision-acr.outputs.acr_login_server }} -p ContainerImageTag=${{ github.sha }}